apiVersion: v1
kind: Service
metadata:
  name: postgres-database
  labels:
    app: postgres-database
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5430
      targetPort: 5430

  selector:
    app: postgres-database